manage_visualization/urls.py
from django.urls import path

from .views import (ClassifierView, DataBagSimplificationView,
                    DataDistributionModalView, DataReductionView,
                    DataRepresentationView, DataVisulizationDashView,
                    DownloadDatasetView, HomePageView, ReductionAlgorithmView)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('data-representation', DataRepresentationView.as_view(),
         name='data-representation'),
    path('data-visualization-dash', DataVisulizationDashView.as_view(),
         name='data-visualization-dash'),
    path('data-reduction', DataReductionView.as_view(),
         name='data-reduction'),
    path('data-distribution', DataDistributionModalView.as_view(),
         name='data-distribution'),
    path('data-reduction-algorithm', ReductionAlgorithmView.as_view(),
         name='data-reduction-algorithm'),
    path('data-bag-simplification', DataBagSimplificationView.as_view(),
         name='data-bag-simplification'),
    path('download-dataset', DownloadDatasetView.as_view(),
         name='download-dataset'),
    path('classifier', ClassifierView.as_view(),
         name='classifier'),
]

mil_visualization/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manage_visualization.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manage_visualization/models.py
from django.db import models


class Reduction(models.Model):
    KPCA = 'kpca'
    FAST_ICA = 'fast_ica'
    ISOMAP = 'isomap'
    LLE = 'lle'
    MDS = 'mds'
    TSNE = 'tsne'
    REDUCTION_METHODS = [
        (KPCA, 'KPCA'),
        (FAST_ICA, 'FastICA'),
        (ISOMAP, 'Isomap'),
        (LLE, 'Locally Linear Embedding'),
        (MDS, 'MDS'),
        (TSNE, 'TSNE')
    ]
    reduction_method = models.CharField(
        max_length=25,
        choices=REDUCTION_METHODS,
        default=KPCA,
    )

    def __str__(self):
        return self.reduction_method


class Algorithm(models.Model):
    algorithm_name = models.SlugField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    reduction = models.ForeignKey(
        Reduction,
        on_delete=models.CASCADE,
        related_name="algorithms",
    )

    def __str__(self):
        return self.algorithm_name

manage_visualization/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.forms import ModelForm

from .models import Reduction


class UploadFileForm(forms.Form):
    DATASETS_EXAMPLES = [
        ('', '---'),
        ('data_gauss', 'data_gauss'),
        ('custom_data_gauss', 'custom_data_gauss'),
        ('musk1_original', 'musk1_original'),
        ('musk1_scaled', 'musk1_scaled'),
        ('musk2_original', 'musk2_original'),
        ('musk2_scaled', 'musk2_scaled'),
        ('fox_original', 'fox_original'),
        ('fox_scaled', 'fox_scaled'),
        ('tiger_original', 'tiger_original'),
        ('tiger_scaled', 'tiger_scaled'),
        ('mutagenesis1_original', 'mutagenesis1_original'),
        ('mutagenesis1_scaled', 'mutagenesis1_scaled'),
        ('mutagenesis2_original', 'mutagenesis2_original'),
        ('mutagenesis2_scaled', 'mutagenesis2_scaled'),
        ('birds_BRCR_original', 'birds_BRCR_original'),
        ('birds_BRCR_scaled', 'birds_BRCR_scaled'),
        ('birds_WIWR_original', 'birds_WIWR_original'),
        ('birds_WIWR_scaled', 'birds_WIWR_scaled'),
        ('corel_african_original', 'corel_african_original'),
        ('corel_african_scaled', 'corel_african_scaled'),
        ('elephant_original', 'elephant_original'),
        ('elephant_scaled', 'elephant_scaled'),
    ]
    # title = forms.CharField(max_length=50, required=False)
    file = forms.FileField(required=False, validators=[
                           FileExtensionValidator(['csv', 'svm'])])
    datasets = forms.ChoiceField(choices=DATASETS_EXAMPLES, required=False)


class ReductionForm(ModelForm):
    ALGORITHMS = [
        ('linear', 'Linear'),
        ('poly', 'Poly'),
        ('rbf', 'RBF')
    ]
    BAG_SIMPLIFICATION = [
        ('', 'None'),
        ('kde', 'KDE'),
        ('max', 'Max'),
        ('min', 'Min'),
        ('mean', 'Mean'),
        ('max+min', 'Max-Min'),
        ('max+min+mean', 'Max-Min-Mean')
    ]
    algorithms = forms.ChoiceField(
        choices=ALGORITHMS,
        required=False,
        widget=forms.RadioSelect,
        initial='linear'
    )
    n_components = forms.IntegerField(min_value=0, initial=4)
    by_bag = forms.BooleanField(required=False)
    kde = forms.BooleanField(required=False)
    bag_simplification = forms.ChoiceField(
        choices=BAG_SIMPLIFICATION,
        required=False,
        widget=forms.RadioSelect
    )

    class Meta:
        model = Reduction
        fields = ['reduction_method']

manage_visualization/views.py
import csv
import json
# import logging
import os
import random as rand
import time
import urllib
from io import BytesIO, StringIO

import numpy as np
import pandas as pd
from bokeh.embed import components
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView, View
from django.views.generic.edit import FormView
from google.cloud import storage
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

from .classifier.simpleMIL import simpleMIL
from .dash_plot.distribution_data import distribtion_data
from .dash_plot.donut_legends import donut_chart
from .dash_plot.interaction_network_radar import network_radar
from .forms import ReductionForm, UploadFileForm
from .models import Reduction
from .reduction_method.bag_simplification import bag_simplification
from .reduction_method.fast_ica import fastICA_reduction
from .reduction_method.isomap import isomap_k
from .reduction_method.kde import kde_process
from .reduction_method.kpca import kpca_kernels
from .reduction_method.lle import locally_linear_embedding_k
from .reduction_method.mds import mds
from .reduction_method.tsne import tsne_reduction
from .utils.utils import (clear_session_vars, data_treatment,
                          generate_gauss_dataset, get_data, get_data_info,
                          load_data_mat, load_mil_data)

# logger = logging.getLogger(__name__)


class HomePageView(FormView):
    template_name = "home.html"
    form_class = UploadFileForm

    def get_success_url(self):
        return '{}?{}'.format(reverse('data-representation'), urllib.parse.urlencode(self.queryparams))

    def handle_uploaded_file(self, f):
        self.queryparams = {
            'file-mil-data': f.name
        }
        with open(f'media/upload_files/{f.name}', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

    def upload_blob(self, bucket_name, source_file_name, destination_blob_name):
        """Uploads a file to the bucket."""
        # bucket_name = "your-bucket-name"
        # source_file_name = "local/path/to/file"
        # destination_blob_name = "storage-object-name"

        # source_file_name.seek(0)
        # file_handle = BytesIO(source_file_name.read())

        storage_client = storage.Client()
        bucket = storage_client.bucket(bucket_name)
        blob = bucket.blob(destination_blob_name)

        blob.upload_from_file(source_file_name)

        self.queryparams = {
            'file-mil-data': destination_blob_name
        }

    def post(self, request, *args, **kwargs):
        clear_session_vars(request)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            if len(request.FILES) > 0:
                try:
                    # self.handle_uploaded_file(request.FILES['file'])
                    self.upload_blob(
                        'mil-datasets', request.FILES['file'], request.FILES['file'].name)
                except Exception as e:
                    # logger.error(e)
                    messages.error(
                        request, 'Something went wrong when writing to the file.')
                    return self.form_invalid(form)
            elif request.GET.get('datasets') != '':
                self.queryparams = {
                    'mil-data': request.POST.get('datasets')
                }
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class DataRepresentationView(TemplateView):
    # - Adicionar nota en el front acerca de la normalizacion.
    template_name = "data_representation.html"

    def get(self, request, *args, **kwargs):
        clear_session_vars(request)
        context = self.get_context_data(**kwargs)
        if 'error' in context:
            return HttpResponseRedirect(reverse('home'))
        return self.render_to_response(context)

    def get_form(self):
        return ReductionForm()

    def make_blob_public(self, bucket_name, blob_name):
        """Makes a blob publicly accessible."""
        storage_client = storage.Client()
        bucket = storage_client.get_bucket(bucket_name)
        blob = bucket.blob(blob_name)

        blob.make_public()
        return blob.public_url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mil_data = self.request.GET.get('mil-data')
        title_dataset = mil_data
        if mil_data:
            df = load_data_mat(mil_data)
            context['mil_data'] = mil_data
        else:
            try:
                url = self.make_blob_public(
                    'mil-datasets', self.request.GET.get("file-mil-data"))
                df = load_mil_data(url)
                title_dataset = self.request.GET.get('file-mil-data')
            except Exception as e:
                # logger.error(e)
                print(e)
                messages.error(
                    self.request, 'Something went wrong when load the dataset.')
                context = {
                    'error': 'Something went wrong when load the dataset.'}
                return context

        # Normalize data
        df = data_treatment(df, range=(0.00, 1.00))

        self.request.session['df_original'] = df.to_json()
        self.request.session['title_dataset'] = title_dataset

        context['title_dataset'] = title_dataset
        columns = [{'field': f, 'title': f}
                   for f in list(df.columns)]
        columns_describe = [{'field': f, 'title': f}
                            for f in list(df.describe().columns)]
        columns_describe.insert(0, {
            'field': 'index1',
            'title': 'Describe'
        })
        context['data'] = df.to_json(orient='records')
        context['columns'] = columns
        # Add more descriptive information
        df_describe = df.describe()
        df_describe = df_describe.drop(['count'])
        df_describe['index1'] = df_describe.index
        context['data_describe'] = df_describe.to_json(orient='records')
        context['columns_describe'] = columns_describe

        context['reduction_form'] = self.get_form()
        context['max_components'] = len(columns) - 2

        data_info = get_data_info(df)
        context.update(data_info)

        return context


class DataReductionView(View):

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        return JsonResponse(context)

    def get_context_data(self, **kwargs):
        df_main_json = self.request.session.get('df_original')
        df_main = pd.DataFrame(json.loads(df_main_json))
        df_main_reduction = None
        error = False
        error_message = ''

        self.request.session['reduction_info'] = json.dumps(self.request.POST)

        try:
            if self.request.POST.get('bag_simplification') == 'kde':
                df_main, pdf, pdf2 = kde_process(df_main)
            elif self.request.POST.get('bag_simplification') != 'None' and self.request.POST.get('bag_simplification') != '':
                df_main = bag_simplification(
                    df_main, self.request.POST.get('bag_simplification'))

            if self.request.POST.get('reduction_method') == 'kpca':
                df_main_reduction = kpca_kernels(
                    df_main,
                    kernel=self.request.POST.get('algorithms'),
                    by_bag=self.request.POST.get('by_bag'),
                    n_components=int(self.request.POST.get('n_components'))
                )
            if self.request.POST.get('reduction_method') == 'fast_ica':
                df_main_reduction = fastICA_reduction(
                    df_main,
                    algorithm=self.request.POST.get('algorithms'),
                    by_bag=self.request.POST.get('by_bag'),
                    n_components=int(self.request.POST.get('n_components'))
                )
            if self.request.POST.get('reduction_method') == 'isomap':
                df_main_reduction = isomap_k(
                    df_main,
                    by_bag=self.request.POST.get('by_bag'),
                    n_components=int(self.request.POST.get('n_components'))
                )
            if self.request.POST.get('reduction_method') == 'lle':
                df_main_reduction = locally_linear_embedding_k(
                    df_main,
                    eigen_solver=self.request.POST.get('algorithms'),
                    n_components=int(self.request.POST.get('n_components'))
                )
            if self.request.POST.get('reduction_method') == 'mds':
                df_main_reduction = mds(
                    df_main,
                    by_bag=self.request.POST.get('by_bag'),
                    n_components=int(self.request.POST.get('n_components'))
                )
            if self.request.POST.get('reduction_method') == 'tsne':
                df_main_reduction = tsne_reduction(
                    df_main,
                    by_bag=self.request.POST.get('by_bag'),
                    n_components=int(self.request.POST.get('n_components'))
                )
        except Exception as e:
            # logger.error(e)
            # messages.error(
            #     self.request, 'Something went wrong when try to reduce the dataset.')
            error_message = str(e)
            error = True

        if error:
            context = {

manage_visualization/templates/base.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Multi Instance Learning Visualization">
    <meta name="author" content="jeliecerv">
    <title>
        {% block title %}
        {{ page_title|default:"Untitled Page" }}
        {% endblock title %}
    </title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
        integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/css/bootstrap-slider.min.css"
        integrity="sha256-G3IAYJYIQvZgPksNQDbjvxd/Ca1SfCDFwu2s2lt0oGo=" crossorigin="anonymous" />


    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'css/loader.css' %}" rel="stylesheet">

    {% block css_links %}{% endblock css_links %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar home -->
                    <div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100">
                        <a class="nav-link" href="/" role="button" aria-haspopup="true" aria-expanded="false"
                            data-toggle="tooltip" title="Home">
                            <i class="fas fa-home fa-fw fa-2x"></i>
                        </a>
                    </div>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        {% block icon_bar %}{% endblock icon_bar %}

                        <!-- Nav Item - Alerts -->
                        <li class="nav-item no-arrow mx-1">
                            <a class="nav-link" href="{% static 'user_manual/user_manual.pdf' %}" role="button"
                                aria-haspopup="true" aria-expanded="false" target="_blank" data-toggle="tooltip"
                                title="Help">
                                <i class="fas fa-question-circle fa-fw fa-lg"></i>
                            </a>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <div class="row top-messages" {% if not messages %}style="display:none" {% endif %}>
                    {% for message in messages %}
                    <div class="col-lg-6 offset-3">
                        <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ message }}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col-lg-6 offset-3 top-message-error" style="display:none">
                        <div class="alert alert-dismissible alert-error">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        </div>
                    </div>
                </div>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        {% block title_content %}<h1 class="h3 mb-0 text-gray-800"></h1>{% endblock title_content %}
                    </div>

                    <!-- Content Row -->

                    <div class="row">

                        <!-- Area Chart -->
                        <div class="col-xl-12 col-lg-12">
                            {% block content %}
                            <p>Placeholder text in base template. Replace with page content.</p>
                            {% endblock content %}
                        </div>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            {% block footer %}
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; 2019</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
            {% endblock footer %}


        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Modal -->
    <div class="modal fade" id="dataModal" tabindex="-1" role="dialog" aria-labelledby="dataModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="dataModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <a class="btn btn-primary display-none download-link" href="#">Download</a>
                    <a class="btn btn-primary display-none classify" href="#">Classify</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <input id="urlReductionAlgorithm" type="hidden" value="{% url 'data-reduction-algorithm' %}">

    <!-- Loader -->
    <div class="loader-backdrop modal-backdrop fade no-show">
        <div class="loader">
            <p>Loading...</p>
            <div class="loader-inner"></div>
            <div class="loader-inner"></div>
            <div class="loader-inner"></div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/js/all.min.js"
        integrity="sha256-xzrHBImM2jn9oDLORlHS1/0ekn1VyypEkV1ALvUx8lU=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/bootstrap-slider.min.js"
        integrity="sha256-oj52qvIP5c7N6lZZoh9z3OYacAIOjsROAcZBHUaJMyw=" crossorigin="anonymous"></script>

    {% block js_libs %}{% endblock js_libs %}

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>

    {% block custom_js %}{% endblock custom_js %}

</body>

</html>

manage_visualization/templates/data_distribution.html
{% load plotly_dash %}

<div>
    {% plotly_app name="distribtion_data" ratio=0.85 %}
</div>

manage_visualization/templates/data_visualization_dash.html
{% extends "base.html" %}
{% load plotly_dash %}

{% block title %}Data Visualization{% endblock title %}

{% block css_links %}
{% endblock css_links %}

{% block js_libs %}
{% endblock js_libs %}

{% block custom_js %}

{% endblock custom_js %}

{% block title_content %}
<h1 class="h3 mb-0 text-gray-800">MIL Visualization / Data Representation</h1>
{% endblock title_content %}

{% block content %}
<div class="row">
  <h2 class="text-gray-800">{{ title_dataset }}</h2>
</div>

<div class="row">
  <!-- Area Chart -->
  <div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Graph Chart</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-area">
          {% plotly_app name="network_radar" ratio=0.5 %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

manage_visualization/templates/list_feature.html
<div>
    <div>
        <p>Select the characteristics you <b>DO NOT</b> want to be exported or part of the classification.</p>
    </div>
    <div>
        <p><a href="#" class="select-all-feature">Select All</a></p>
    </div>
    {% for feature in features %}
    <label class="checkbox-inline">
        <input type="checkbox" value="{{ feature }}" data-field="{{ feature }}"> {{ feature }}
    </label>
    {% endfor %}
</div>

manage_visualization/templates/reduction_algorithm.html
<div>

</div>

manage_visualization/templates/reduction_form.html
<form id="reduction-form" method="post" data-url="{% url 'data-reduction' %}">{% csrf_token %}
    <div class="form-group">
        <label data-toggle="tooltip"
            title="Apply over the data some reduction method: TSNE, MDS, LLE, Isomap, FastICA, KPCA.">{{ reduction_form.reduction_method.label }}</label>
        <select name="reduction_method" class="form-control" id="id_reduction_method"
            {% if disabled %}disabled{% endif %}>
            {% for reduction_method  in reduction_form.reduction_method  %}
            {{ reduction_method }}
            {% endfor %}
        </select>
    </div>
    <div class="form-group" id="algorithms_reduction">
        <label data-toggle="tooltip"
            title="Can be a kernel or an algorithm, it depends for reduction method choose">Algorithms</label><br>
        <div id="radioBtnAlgorithm" class="btn-group radio-btn">
            {% for algorithm in reduction_form.algorithms.field.choices %}
            <a class="btn btn-primary btn-sm {% if algorithm.0 == reduction_form.algorithms.value %}active{% else %}notActive{% endif %} {% if disabled %}disabled{% endif %}"
                data-toggle="algorithms" data-title="{{ algorithm.0 }}">
                {{ algorithm.1 }}
            </a>
            {% endfor %}
        </div>
        <input type="hidden" name="algorithms" id="algorithms" value="{{ reduction_form.algorithms.value }}"
            class="{% if disabled %}disabled{% endif %}">
    </div>
    <div class="form-group">
        <label data-toggle="tooltip"
            title="Number of components in which the data will be reduced">{{ reduction_form.n_components.label }}</label>
        <br>
        <b>1</b>
        <input id="id_n_components" name="n_components" data-slider-id='id_n_componentsSlider' type="number" required
            data-slider-min="1" data-slider-max="{{ max_components }}" data-slider-step="1"
            data-slider-value="{{ reduction_form.n_components.value }}" {% if disabled %}data-slider-enabled="false"
            {% endif %} />
        <b>{{ max_components }}</b>
        <br>
        <span id="id_n_componentsSliderValLabel"><b>Current Value: </b><span
                id="id_n_componentsSliderVal">{{ reduction_form.n_components.value }}</span></span>
    </div>
    <div class="form-group">
        <label class="checkbox-inline checbox-switch switch-primary">
            <input type="checkbox" name="by_bag" {% if disabled %}disabled{% endif %}
                {% if reduction_form.by_bag.value %}checked{% endif %} />
            <span></span>
            <label data-toggle="tooltip" title="Allow do reduction only in bag-level instead of instance-level">By
                bag</label>
        </label>
    </div>
    {% if disabled %}
    <div class="form-group" id="algorithms_reduction">
        <label data-toggle="tooltip" title="This option allows reducting the number of instance in each bag">Bag
            simplification</label><br>
        <div id="radioBtn" class="btn-group radio-btn">
            {% for bs in reduction_form.bag_simplification.field.choices %}
            <a class="disabled btn btn-primary btn-sm {% if bs.0 == reduction_form.bag_simplification.value %}active{% else %}notActive{% endif %}"
                data-toggle="bag_simplification" data-title="{{ bs.0 }}">
                {{ bs.1 }}
            </a>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    <input type="submit" class="btn btn-primary" value="Apply">
</form>